### ISSUE TITLE
Feature interaction: project duplicate + swimlanes

### ISSUE THREAD

**Issue by psybers** [nephila/python-taiga#169]
## Description

It appears there is a bit of a feature interaction between the ability to duplicate a project (#161) and the new swimlanes support (#162).  The issue is that when duplicating a project, Taiga (apparently) returns a `swimlanes` parameter with no value.  So Python sets the value to `None` and then attempts to call parse with that value.  This results in the following crash:

```python
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    newProject = project.duplicate(name=newProjectName,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/taiga/models/models.py", line 1769, in duplicate
    return self.parse(self.requester, response.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/taiga/models/base.py", line 199, in parse
    entry[key_to_parse] = cls_to_parse.parse(requester, entry[key_to_parse])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/taiga/models/base.py", line 107, in parse
    for entry in entries:
TypeError: 'NoneType' object is not iterable
```

The problem is in `base.py` on line 107: https://github.com/nephila/python-taiga/blob/dce5ae0141b87a571389ae95e80d7bf46d48fc23/taiga/models/base.py#L107

Here, `entries` winds up being `None`.  I believe this is really a shortcoming of the Taiga API response.  It should either not send `swimlanes` in the response or it should send it with an empty list.  At any rate, I would recommend placing an `if entries:` before this line to avoid problems such as this.  In this case, it would simply wind up with an empty swimlanes attribute, which is correct.

## Steps to reproduce

Call `duplicate()` on a project:

```python
api = TaigaAPI()
api.auth(username=username, password=password)
project = api.projects.get_by_slug('nephila')
newProject = project.duplicate(name='test', description='This is a test')
```

## Versions

python-taiga: 1.3.0

## Expected behaviour

No crash.  The project duplicates and returns a proper `Project` object.

## Actual behaviour

Crashes.  Though the project *is* duplicated on Taiga's side.

**Comment by protoroto** [comment]
@psybers Thanks for the detailed explaination: @PSzczepanski1996 already opened a PR fixing this, but I'd love to have a test covering this case. @yakky what do you think? 
We could mock a response after a `duplicate()` with `swimlanes` parameter empty (like we do in all other test cases, like https://github.com/nephila/python-taiga/blob/master/tests/test_epics.py#L16 here, maybe taking a real response - with fake data, of course) and assert that no exception is thrown.

**Comment by protoroto** [comment]
@psybers Actually, I don't have a running Taiga + Python Taiga instance to see what kind of response a `duplicate()` will return: if you provide me one, I can add a test to @PSzczepanski1996 PR to cover this case.

**Comment by PSzczepanski1996** [comment]
That's fine, I'm little busy with work at my workplace so if you can write test - just do that.
Thanks!

**Comment by psybers** [comment]
@protoroto according to the API docs (https://docs.taiga.io/api.html#projects-duplicate) it just returns a project detail object:

https://docs.taiga.io/api.html#object-project-detail

**Comment by protoroto** [comment]
@psybers @PSzczepanski1996 Sorry for the delay, sadly I didn't had much time to work on this. I'll try next week to write a test and add it to @PSzczepanski1996 pr

**Comment by kodyo** [comment]
More observation: This issue doesn't appear to be limited to projects created from duplicate(). If a project has never had a swimlane created, the api.projects.get_by_slug() function crashes when it tries to enumerate swimlanes. The parse() function in base.py was failing because there are no swimlanes to enumerate. In my case, the Kanban module had not been enabled, so swimlane functionality wasn't even visible.

The get_by_slug() function succeeds after enabling the Kanban module in a project, manually creating a swimlane, then disabling the Kanban module.

**Comment by LuminatiHD** [comment]
hello, what is the status on this? I'm experiencing the same errors.

**Comment by InsaneCake** [comment]
Have issue with `api.projects.get_by_slug()`.
Creating swimlane works as a workaround (thanks @kodyo), but permanent keeping single swimlane just for script leads to worse usability overall due to limited kanban space on web page.

For those who keep getting `TypeError: 'NoneType' object is not iterable` and don't need new duplication and swimlane functionality - rollback to 1.2.0 is also an option:
`pip install --force-reinstall -v "python-taiga==1.2.0"`

**Comment by protoroto** [comment]
Hi everyone: sorry for the delayed answer, but I haven't had time for looking into this.
As I said before, I'd like to add a test for this, but I haven't had time.
I'll try to look into this next week, I should be able to at least try to test the `get_project_by_slug` with a project with no swimlanes and see what is the API response from Taiga, and build a test from there.

**Comment by protoroto** [comment]
@InsaneCake @LuminatiHD @kodyo @psybers @PSzczepanski1996 I've just released 1.3.1 version that should address this issue. Could you please check if everything is working as expected now?

**Comment by psybers** [comment]
I *think* this is fixed.  The reason I am not 100% sure is that my test code (the code above to reproduce) gives a HTTP 500 error on some of my projects. But it did work for *one* project.

So I think the bug, as reported, is probably fixed but there is some other issue going on with duplicate().  Or the Taiga servers are having an issue.

**Comment by psybers** [comment]
Again, there was no error for that one case... but it didn't duplicate the swimlanes (as I expected).

**Comment by psybers** [comment]
I think the lack of duplicated swimlanes is just a Taiga API thing.  So nothing to fix there.  But I still don't know why most of the projects I tried to duplicate now give a 500 error.  But again, it feels like that is more of an issue on their side and this bug (as reported) feels fixed to me.

**Comment by protoroto** [comment]
@psybers Thanks for the feedback: I'm going to leave this open for a few days and then I'm going to close it, if you have new info about this please report again and we'll try to look into it.

**Comment by protoroto** [comment]
I'm closing this, because it should be fixed with 1.3.1 release. If anyone experience the same problem, feel free to open a new issue referencing this one.
